### ISSUE TITLE
Output to systemd journald

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/log#5]
https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html
https://github.com/coreos/go-systemd

**Comment by nojima** [comment]
Proposal: separate log field for "TOPIC"

Many applications have multiple streams of logs such as access log, error log, etc.
I want to handle these logs separately by our log transfer agent.
Since systemd service have only one unit name, we must include information to distinguish multiple log streams.

There are two possible ways to include the name of a log stream, or TOPIC:
1. Include a TOPIC in message itself encoded in JSON.
2. Include a TOPIC as a separate log field.

Approach 1 needs extra information that indicate whether a message is encoded in JSON or not.
The information must be provided in configuration files.
That's messy.

Therefore, I think approach 2 is better way to go.
We need no extra information to handle logs.
If there are no TOPIC field in a log entry, we can use the unit name as topic instead.

**Comment by ymmt2005** [comment]
As topic is a mandatory field for `cybozu-go/log`, we can just output TOPIC field for systemd-journald.

**Comment by ymmt2005** [comment]
By the end of Apr. 2017.

**Comment by ymmt2005** [comment]
As we have experienced a lot of troubles and bugs with journald, we decide to cancel this task.
cybozu-go/log will never output logs directly to journald.
